const Constant = {
  SplashScreenHeading: 'Design System',
  SplashScreenSubHeading: 'Fully coded React Native components.',
  homeHeaderTitle: 'Home',
  homeScreenInputText: 'What are you looking for?',
  searchPlus: 'search-plus',
  diamond: 'diamond',
  beauty: 'Beauty',
  shoppingBag: 'shopping-bag',
  fashion: 'Fashion',
  iceCreamText: 'Ice cream is made with carrageenan and milk, sugar',
  flowerText: 'Is makeup one of your daily esse my self ajinkya dude',
  girlText: 'Coffee is more than just a drink: It"s my self ajinkya dude',
  manText: 'Fashion is a popular style especially my self ajinkya dude',
  natureText: 'Argon is a great free package my self ajinkya dude',
  backLogo: 'chevron-back-outline',
  accountCreate: 'Create Account',
  bellIcon: 'bell-badge',
  shoppingIcon: 'shopping',
  accountUnChecked: 'checkbox-blank-outline',
  accountChecked: 'checkbox-marked',
  signUpText: 'Sign up with',
  gitHubIcon: 'github',
  gitHubText: 'GITHUB',
  googleText: 'GOOGLE',
  signUpCredentialText: 'Or sign up with credentials',
  graduationIcon: 'graduation-cap',
  inputPlaceholderName: 'Name',
  inputPlaceholderEmail: 'Email',
  envelopeIcon: 'envelope',
  inputPlaceholder: 'Password',
  passwordIcon: 'unlock-alt',
  passwordStreghtText: 'password strenght:',
  strongText: 'Strong',
  checkFirstText: 'I agree with the',
  checkSecondText: 'Privacy Policy',
  createButton: 'CREATE ACCOUNT',
  profileText: 'Profile',
  componentCheck: 'check-circle',
  componentError: 'globe',
};

export default Constant;
